config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :events
  resources :posts
  resources :post_categories

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'pages#home'

  get 'activity_logs', to: 'activity_logs#index'
  get 'activity_logs/:action_subject', to: 'activity_logs#action_subject', as: 'activity_logs_source'

  namespace :users do
    get '/:uuid', to: 'profiles#show', as: 'profile'
    get '/name/:login', to: 'profiles#show', as: 'profile_by_login'

    get '/edit/:uuid', to: 'profiles#edit', as: 'edit_profile'
    get '/followers/:uuid', to: 'profiles#show_followers', as: :show_followers
    get '/following/:uuid', to: 'profiles#show_following', as: :show_following
    get '/blocked/:uuid', to: 'profiles#show_blocked', as: :show_blocked

    post '/edit/:uuid', to: 'profiles#update', as: 'update_profile'
    post '/block/:uuid', to: 'profiles#block', as: 'profile_block'
    post '/unblock/:uuid', to: 'profiles#unblock', as: 'profile_unblock'
    post '/follow/:uuid', to: 'profiles#follow', as: 'profile_follow'
    post '/unfollow/:uuid', to: 'profiles#unfollow', as: 'profile_unfollow'
  end

  get '/messages/:user_uuid', to: 'messages#index', as: :users_conversations
  get '/messages/:sender_uuid/:adressee_id', to: 'messages#new', as: :messages_new
  get '/conversation/:thread_uuid', to: 'messages#show', as: :conversation_show
  post '/conversation/:thread_uuid', to: 'messages#create', as: :messages_create
  delete '/messages/:message_id', to: 'messages#destroy', as: :destroy_message

  post 'like/:kind/:id', to: 'reactions#like', as: 'like_activity'
  delete 'dislike/:kind/:id', to: 'reactions#dislike', as: 'dislike_activity'

  get 'comment/:kind/:id', to: 'comments#new', as: 'new_comment'
  post 'comment/:kind/:id', to: 'comments#create', as: 'create_comment'
  delete 'comment/:id', to: 'comments#destroy', as: 'destroy_comment'

  get '/posts/user/:uuid', to: 'posts#users_posts', as: :users_posts
  get '/posts/for_you/:uuid', to: 'posts#for_you', as: :posts_for_you
  get '/posts/popular/top', to: 'posts#popular', as: :posts_popular

  get '/events/user/:uuid', to: 'events#users_events', as: :users_events
  post 'events/:id/buy_ticket', to: 'events#buy_ticket', as: :buy_ticket_to_event
  get '/user/:uuid/tickets', to: 'events#show_tickets', as: :show_tickets


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_rich_text :about_me

  has_many :posts
  has_many :activity_logs
  has_many :events
  has_many :tickets
  has_many :comments

  has_many :own_threads, class_name: 'MessageThread',
                         foreign_key: :sender_id
  has_many :other_threads, class_name: 'MessageThread',
                           foreign_key: :adressee_id

  has_many :active_obserwations, class_name: 'Observation',
                                 foreign_key: :follower_id,
                                 dependent: :destroy
  has_many :following, through: :active_obserwations, source: :followed

  has_many :passive_obserwations, class_name: 'Observation',
                                  foreign_key: :followed_id,
                                  dependent: :destroy

  has_many :followers, through: :passive_obserwations, source: :follower

  has_many :active_blockade, class_name: 'Blockade',
                             foreign_key: :blocker_id,
                             dependent: :destroy

  has_many :blocked_users, through: :active_blockade, source: :blocked

  has_many :passive_blockade, class_name: 'Blockade',
                              foreign_key: :blocked_id,
                              dependent: :destroy

  has_many :blockers, through: :passive_blockade, source: :blocker

  validates :login, uniqueness: true

  def threads
    own_threads + other_threads
  end

  def blocked?(other_user)
    blocked_users.pluck(:id).include?(other_user.id)
  end

  def following?(other_user)
    following_users_ids.include?(other_user.id)
  end

  def following_users_ids
    following.pluck(:id)
  end

  def full_name
    return "#{first_name} #{last_name}" if all_personal_data_filled?

    email
  end

  def all_personal_data_filled?
    first_name.present? && last_name.present? &&
      login.present?
  end

  def avatar_preload
    avatar.attached? ? avatar : ''
  end

  def mini_avatar
    avatar.variant(resize_to_limit: [150, 150]).processed
  end
end

app/controllers/concerns/authentication/user_controller.rb
# frozen_string_literal: true

module Authentication
  module UserController
    extend ActiveSupport::Concern

    private

    def check_ability
      return if user_signed_in?

      render :file => "public/401.html", :status => :unauthorized
    end

    def user_log_in?
      return if user_signed_in?

      redirect_to new_user_session_path, alert: 'Aby wykonać akcję musisz się zarejestrować.'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
module Users
  class ProfilesController < CommonActionController
    include ::ActivityLogs::Loggable

    before_action :user_log_in?
    before_action :set_object, only: %i[show edit update block follow unblock unfollow show_following show_followers]
    before_action :validate_password, only: %i[update]
    after_action :create_log, only: %i[update block follow unblock unfollow]
    before_action :load_action_context, only: %i[update block follow unfollow unblock]
    before_action :self_action, only: %i[follow block unfollow unblock]
    after_action :broadcast_stats_changes, only: %i[follow block unfollow unblock]
    after_action :broadcast_changes, only: %i[follow block unfollow unblock]

    def show
      redirect_to root_path, alert: 'Nie znaleziono użytkownika' if @object.blank?
      user_presenter
    end

    def show_followers
      @followers = @object.followers.includes(avatar_attachment: :blob)
    end

    def show_following
      @following = @object.following.includes(avatar_attachment: :blob)
    end

    def show_blocked
      @blocked = current_user.blocked_users.includes(avatar_attachment: :blob)
    end

    def edit
      redirect_to root_path, alert: 'Nie znaleziono użytkownika' if @object.blank?
    end

    def update
      respond_to do |format|
        if @action_context.perform
          format.html { redirect_to users_profile_path(@object.uuid), notice: notice }
          broadcast_notice
        else
          format.html { redirect_to users_edit_profile_path(@object.uuid), alert: alert }
          broadcast_alert
        end
      end
    end

    def block
      respond_to do |format|
        if @action_context.perform
          format.html { redirect_to users_profile_path(@object.uuid), notice: notice }
          format.turbo_stream {}
          broadcast_notice
        else
          format.html { redirect_to users_profile_path(@object.uuid), alert: alert }
          broadcast_alert
        end
      end
    end

    def unblock
      respond_to do |format|
        if @action_context.perform
          format.html { redirect_to users_profile_path(@object.uuid), notice: notice }
          format.turbo_stream {}
          broadcast_notice
        else
          format.html { redirect_to users_profile_path(@object.uuid), alert: alert }
          broadcast_alert
        end
      end
    end

    def follow
      respond_to do |format|
        if @action_context.perform
          format.html { redirect_to users_profile_path(@object.uuid), notice: notice }
          format.turbo_stream {}
          broadcast_notice
        else
          format.html { redirect_to users_profile_path(@object.uuid), alert: alert }
          broadcast_alert
        end
      end
    end

    def unfollow
      respond_to do |format|
        if @action_context.perform
          format.html { redirect_to users_profile_path(@object.uuid), notice: notice }
          format.turbo_stream {}
          broadcast_notice
        else
          format.html { redirect_to users_profile_path(@object.uuid), alert: alert }
          broadcast_alert
        end
      end
    end

    def user_presenter
      @user_presenter ||= ::UserPresenter.new(@object)
    end

    private

    def broadcast_changes
      Turbo::StreamsChannel.broadcast_replace_to :"dynamic_users_list_#{current_user.uuid}",
                                                 target: "user_#{@object.uuid}",
                                                 partial: 'users/profiles/user_row',
                                                 locals: { user: @object, current_user: current_user }
    end

    def broadcast_stats_changes
      Turbo::StreamsChannel.broadcast_replace_to :"dynamic_stats_#{current_user.uuid}",
                                                 target: "user_stats_#{current_user.uuid}",
                                                 partial: 'users/profiles/stats_table',
                                                 locals: { presenter: current_user_presenter, current_user: current_user }
    end

    def current_user_presenter
      ::UserPresenter.new(current_user.reload)
    end

    def permitted_params
      params.fetch(:user, params).permit!
    end

    def set_object
      @object = User.find_by(uuid: params[:uuid]) || User.find_by(login: params[:login])
    end

    def self_action
      return unless current_user.uuid == @object.uuid

      broadcast_alert 'Nie możesz wykonać tej akcji'
      redirect_to users_profile_path(@object.uuid), alert: 'Nie możesz wykonać tej akcji'
    end

    def action_subject
      :user
    end

    def passowrd
      params.dig(:user, :password)
    end

    def validate_password
      return if current_user.valid_password?(passowrd)

      broadcast_alert 'Błędne hasło'
      redirect_to users_edit_profile_path(current_user.uuid), alert: 'Błędne hasło'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include ::ActivityLogs::Loggable
  # before_action :configure_sign_in_params, only: [:create]
  after_action :create_log, only: :create
  before_action :create_log, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private

  def action_subject
    :login
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def following_partial_name(user)
    partial_prefix + (current_user.following?(user) ? 'others_actions/unfollow' : 'others_actions/follow')
  end

  def block_partial_name(user)
    partial_prefix + (current_user.blocked?(user) ? 'others_actions/unblock' : 'others_actions/block')
  end

  def action_partial_name(user)
    partial_prefix + (owner?(user) ? 'owner_actions/actions' : 'others_actions/available_actions')
  end

  def owner?(user)
    current_user.uuid == user.uuid
  end

  def partial_prefix
    'users/profiles/'
  end
end

app/views/users/profiles/_form.html.erb
<%= form_with(model: user, method: :post, url: users_update_profile_path(user.uuid)) do |form| %>
  <div class="form-group mb-2">
    <%= form.label 'Imię' %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label 'Nazwisko' %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :login %>
    <%= form.text_field :login, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label 'O mnie' %>
    <%= form.rich_text_area :about_me, class: "form-control mb-2" %>
  </div>

  <%= content_tag :div, class: "form-group", data: { controller: 'image-upload-preview' } do %>
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control", data: { target: 'image-upload-preview.input', action: 'image-upload-preview#setImagePreview' }%>
    <%= image_tag user.avatar_preload, class: 'my-3', 
          data: { target: 'image-upload-preview.preview' }  if user %>
  <% end %>

  <div class="form-group mb-2">
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: :off, class: "form-control" %>
  </div>

  <div>
    <%= form.submit 'Zapisz', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/users/profiles/_owner_stats.html.erb
<li class="list-group-item d-flex align-items-start">
  <div class="ms-2 me-auto">
    <%= link_to 'Zablokowani użytkownicy', users_show_blocked_path(current_user.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0'%>
  </div>
  <span class="badge bg-primary rounded-pill">
    <%= presenter.total_blocked %>
  </span>
</li>

app/views/users/profiles/_stats_table.html.erb
<%= content_tag :div, id: "user_stats_#{presenter.uuid}" do %>
  <ol class="list-group">
    <li class="list-group-item d-flex align-items-start">
      <div class="ms-2 me-auto">
        <%= link_to 'Obserwujący', users_show_followers_path(presenter.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0'%>
      </div>
      <span class="badge bg-primary rounded-pill">
        <%= presenter.total_followers%>
      </span>
    </li>
    <li class="list-group-item d-flex align-items-start">
      <div class="ms-2 me-auto">
        <%= link_to 'Obserwowani', users_show_following_path(presenter.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0'%>
      </div>
      <span class="badge bg-primary rounded-pill">
        <%= presenter.total_followed %>
      </span>
    </li>
    <li class="list-group-item d-flex align-items-start">
      <div class="ms-2 me-auto">
        <%= link_to 'Posty', users_posts_path(presenter.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0' %>
      </div>
      <span class="badge bg-primary rounded-pill">
        <%= presenter.total_posts%>
      </span>
    </li>
    <li class="list-group-item d-flex align-items-start">
      <div class="ms-2 me-auto">
        <%= link_to 'Wydarzenia', users_events_path(presenter.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0' %>
      </div>
      <span class="badge bg-primary rounded-pill">
        <%= presenter.total_events%>
      </span>
    </li>

    <!---%= render 'owner_stats', presenter: presenter if owner?(presenter.user)%><!-->

    <% if current_user == presenter.user %>
      <li class="list-group-item d-flex align-items-start">
        <div class="ms-2 me-auto">
          <%= link_to 'Zablokowani użytkownicy', users_show_blocked_path(current_user.uuid), data: { turbo_frame: :dynamic_content }, class: 'link-underline link-underline-opacity-0'%>
        </div>
        <span class="badge bg-primary rounded-pill">
          <%= presenter.total_blocked %>
        </span>
      </li>
    <% end %>
  </ol>
<% end %>

app/views/users/profiles/_user_actions_row.html.erb
<div class='col align-text-middle'>
  <% if current_user.following?(user) %>
    <%= button_to "Obserwujesz", users_profile_unfollow_path(user.uuid), method: :post, class: 'btn btn-success mx-2 my-auto', data: { turbo_method: :post } %>
  <% else %>
    <%= button_to "Obserwuj", users_profile_follow_path(user.uuid), method: :post, class: 'btn btn-outline-success mx-2 my-auto', data: { turbo_method: :post } %>
  <% end %>
</div>

<div class='col align-text-middle'>
  <% if current_user.blocked?(user) %>
    <%= button_to "Zablokowany", users_profile_unblock_path(user.uuid), method: :post, class: 'btn btn-danger mx-2 my-auto', data: { turbo_method: :post } %>
  <% else %>
    <%= button_to "Zablokuj", users_profile_block_path(user.uuid), method: :post, class: 'btn btn-outline-danger mx-2 my-auto', data: { turbo_method: :post } %>
  <% end %>
</div>

app/views/users/profiles/_user_row.html.erb
<div class="row rounded-3 grey my-3 p-3" id=<%= "user_#{user.uuid}"%>>
  <div class='col' style="min-width: 150px">
    <% if user.avatar.content_type.in?(%w[image/jpeg image/png])%>
      <%= image_tag user.mini_avatar, class: 'rounded-circle'%>
    <% end %>
  </div>

  <div class='col align-text-middle align-middle'>
      <%= link_to user.full_name, users_profile_path(user.uuid), class: 'btn btn-outline-primary my-auto', data: { turbo: false } %>
  </div>

  <% if current_user != user %>
    
    <div class='col align-text-middle'>
      <% if current_user.following?(user) %>
        <%= button_to "Obserwujesz", users_profile_unfollow_path(user.uuid), method: :post, class: 'btn btn-success mx-2 my-auto', data: { turbo_method: :post } %>
      <% else %>
        <%= button_to "Obserwuj", users_profile_follow_path(user.uuid), method: :post, class: 'btn btn-outline-success mx-2 my-auto', data: { turbo_method: :post } %>
      <% end %>
    </div>

    <div class='col align-text-middle'>
      <% if current_user.blocked?(user) %>
        <%= button_to "Zablokowany", users_profile_unblock_path(user.uuid), method: :post, class: 'btn btn-danger mx-2 my-auto', data: { turbo_method: :post } %>
      <% else %>
        <%= button_to "Zablokuj", users_profile_block_path(user.uuid), method: :post, class: 'btn btn-outline-danger mx-2 my-auto', data: { turbo_method: :post } %>
      <% end %>
    </div>

  <% else %>
    <div class="col"></div>
    <div class="col"></div>
  <% end %>
</div>

app/views/users/profiles/edit.html.erb
<h1> Edytuj profil </h1>

<%= render 'form', user: @object %>

app/views/users/profiles/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-4">
      <%= image_tag @user_presenter.avatar_picture, class: 'img-thumbnail rounded-circle', style: 'width: 300px'%>
    </div>    
    
    <div class="col-8" style="max-height: 300px">
      <div class="row">
        <div class = 'col'>
          <h2><%= @user_presenter.full_name %></h2>
        </div>
        <div class = 'col-8'>
          <%= render action_partial_name(@user_presenter.user), presenter: @user_presenter %>
        </div>
      </div>
      <div class="row">
        <%= @user_presenter.about_me %>
      </div>
    </div>
  </div>
  <div class="row my-5">
    <div class="col-4">
      <%= turbo_stream_from :"dynamic_stats_#{@user_presenter.uuid}"%>
      <%= render 'stats_table', presenter: @user_presenter %>
    </div>
    <div class="col-8">
      <%= turbo_stream_from :"dynamic_users_list_#{current_user.uuid}" %>
      <%= turbo_frame_tag :dynamic_content, src: users_posts_path(@user_presenter.uuid), data: { missing: "show" }%>
    </div>
  </div>
</div>

app/views/users/profiles/show_blocked.html.erb
<%= turbo_frame_tag :dynamic_content do %>
  <% @blocked.each do |user| %>
    <%= render 'user_row', user: user %>
  <% end %>
<% end %>

app/views/users/profiles/show_followers.html.erb
<%= turbo_frame_tag :dynamic_content do %>
  <div class="container text-center">
    <% @followers.each do |user| %>
      <%= render 'user_row', user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/profiles/show_following.html.erb
<%= turbo_frame_tag :dynamic_content do %>
  <div id="posts">
    <div id="anchorLink">
      <div class="container text-center">
        <% @following.each do |user| %>          
          <%= render 'user_row', user: user, following: true %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>