config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :events
  resources :posts
  resources :post_categories

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'pages#home'

  get 'activity_logs', to: 'activity_logs#index'
  get 'activity_logs/:action_subject', to: 'activity_logs#action_subject', as: 'activity_logs_source'

  namespace :users do
    get '/:uuid', to: 'profiles#show', as: 'profile'
    get '/name/:login', to: 'profiles#show', as: 'profile_by_login'

    get '/edit/:uuid', to: 'profiles#edit', as: 'edit_profile'
    get '/followers/:uuid', to: 'profiles#show_followers', as: :show_followers
    get '/following/:uuid', to: 'profiles#show_following', as: :show_following
    get '/blocked/:uuid', to: 'profiles#show_blocked', as: :show_blocked

    post '/edit/:uuid', to: 'profiles#update', as: 'update_profile'
    post '/block/:uuid', to: 'profiles#block', as: 'profile_block'
    post '/unblock/:uuid', to: 'profiles#unblock', as: 'profile_unblock'
    post '/follow/:uuid', to: 'profiles#follow', as: 'profile_follow'
    post '/unfollow/:uuid', to: 'profiles#unfollow', as: 'profile_unfollow'
  end

  get '/messages/:user_uuid', to: 'messages#index', as: :users_conversations
  get '/messages/:sender_uuid/:adressee_id', to: 'messages#new', as: :messages_new
  get '/conversation/:thread_uuid', to: 'messages#show', as: :conversation_show
  post '/conversation/:thread_uuid', to: 'messages#create', as: :messages_create
  delete '/messages/:message_id', to: 'messages#destroy', as: :destroy_message

  post 'like/:kind/:id', to: 'reactions#like', as: 'like_activity'
  delete 'dislike/:kind/:id', to: 'reactions#dislike', as: 'dislike_activity'

  get 'comment/:kind/:id', to: 'comments#new', as: 'new_comment'
  post 'comment/:kind/:id', to: 'comments#create', as: 'create_comment'
  delete 'comment/:id', to: 'comments#destroy', as: 'destroy_comment'

  get '/posts/user/:uuid', to: 'posts#users_posts', as: :users_posts
  get '/posts/for_you/:uuid', to: 'posts#for_you', as: :posts_for_you
  get '/posts/popular/top', to: 'posts#popular', as: :posts_popular

  get '/events/user/:uuid', to: 'events#users_events', as: :users_events
  post 'events/:id/buy_ticket', to: 'events#buy_ticket', as: :buy_ticket_to_event
  get '/user/:uuid/tickets', to: 'events#show_tickets', as: :show_tickets


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :message_thread
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < CommonActionController
  include ::ActivityLogs::Loggable
  include ::Toasts::Broadcaster
  include ::PolymorphicLoader

  before_action :load_thread, only: [:create, :new]
  before_action :load_message, only: :destroy
  before_action :load_action_context, only: [:create, :destroy]
  after_action :create_log, only: [:create, :destroy]

 
  def new
    @thread ||= Messages::ThreadFinder.perform(current_user: current_user, other_user: adressee)
    redirect_to conversation_show_path(@thread.uuid)
  end

  def show
    @thread ||= Messages::ThreadFinder.perform(uuid: params[:thread_uuid])
  end

  def index
    @message_threads = MessageThread.by_user(current_user)
  end

  def create
    respond_to do |format|
      if @action_context.perform
        format.html { redirect_to conversation_show_path(@object.uuid), notice: notice }
        broadcast_notice
      else
        format.html { redirect_to conversation_show_path(@object.uuid), alert: alert }
        broadcast_alert
      end
    end
  end

  def destroy
    respond_to do |format|
      if @action_context.perform
        format.html { redirect_to conversation_show_path(@object.message_thread.uuid), notice: notice }
        broadcast_notice
      else
        format.html { redirect_to conversation_show_path(@object.uuid), alert: alert }
        broadcast_alert
      end
    end
  end

  private

  def action_subject
    :message
  end

  def load_thread
    @object ||= Messages::ThreadFinder.perform(uuid: params[:thread_uuid])
  end

  def load_message
    @object ||= Message.find_by(id: params[:message_id])
  end

  def permitted_params
    params.permit!
  end

  def adressee
    User.find_by(id: adressee_id)
  end

  def adressee_id
    params[:adressee_id]
  end
end

app/views/messages/_form.html.erb
<%= turbo_frame_tag :"message_thread_#{thread.uuid}" do%>
  <%= form_with url: messages_create_path(thread_uuid: thread.uuid) do |form| %>
    <div class="form-group my-2">
      <%= form.text_field :content, class: "form-control" %>
    </div>

    <div>
      <%= form.submit 'Wyślij', class: 'btn btn-success btn-sm', data: { turbo: false } %>
    </div>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message)%>" class="row rounded-3 my-1 p-2 w-50 <%= object_author?(message) ? 'blue-bg' : 'green-bg float-end' %>">
  <div class='row'>
    <div class='col-2' style='min-width: 175px;'>
      <% if object_author?(message) %>
        <%= button_to 'Usuń wiadomość', 
              destroy_message_path(message_id: message.id),
              class: 'btn btn-outline-danger my-1 btn-sm', 
              method: :delete, data: { turbo: false } %>
      <% else %>
        <%= link_to message.user.full_name, 
              users_profile_path(message.user.uuid), 
              class: 'btn btn-outline-success btn-sm', 
              data: { turbo: false } %>
      <% end %>
    </div>
    
    <div class='col'>
      <%= message.content %>
    </div>
  </div>
</div>
<div style="clear:both;"></div>

app/views/messages/_thread.html.erb
<div class="row rounded-3 my-1 p-2 w-50 green-bg">
  <div class='row'>
    <div class='col-2' style='min-width: 175px;'>
      <%= link_to thread.sender.full_name, 
            users_profile_path(thread.sender.uuid), 
            class: 'btn btn-outline-primary btn-sm', 
            data: { turbo: false } %>
    </div>

    <div class='col-2' style='min-width: 175px;'>
      <%= link_to thread.adressee.full_name, 
            users_profile_path(thread.adressee.uuid), 
            class: 'btn btn-outline-success btn-sm', 
            data: { turbo: false } %>
    </div>

    <div class='col'>
      <%= link_to 'Idź do konwersacji', 
            conversation_show_path(thread.uuid), 
            class: 'btn btn-primary btn-sm', 
            data: { turbo: false } %>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<h1>Twoje wiadomości:</h1>

<%= render partial: 'thread', collection: @message_threads, as: :thread %>

app/views/messages/new.html.erb
<%= render 'form', thread: @thread %>

app/views/messages/show.html.erb
<h1> <%= "#{@thread.sender.full_name} - #{@thread.adressee.full_name}" %></h1>
<%= render partial: 'message', collection: @thread.messages.order(:created_at), as: :message, locals: { thread: @thread } %>

<%= render 'form', thread: @thread%>