config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :events
  resources :posts
  resources :post_categories

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'pages#home'

  get 'activity_logs', to: 'activity_logs#index'
  get 'activity_logs/:action_subject', to: 'activity_logs#action_subject', as: 'activity_logs_source'

  namespace :users do
    get '/:uuid', to: 'profiles#show', as: 'profile'
    get '/name/:login', to: 'profiles#show', as: 'profile_by_login'

    get '/edit/:uuid', to: 'profiles#edit', as: 'edit_profile'
    get '/followers/:uuid', to: 'profiles#show_followers', as: :show_followers
    get '/following/:uuid', to: 'profiles#show_following', as: :show_following
    get '/blocked/:uuid', to: 'profiles#show_blocked', as: :show_blocked

    post '/edit/:uuid', to: 'profiles#update', as: 'update_profile'
    post '/block/:uuid', to: 'profiles#block', as: 'profile_block'
    post '/unblock/:uuid', to: 'profiles#unblock', as: 'profile_unblock'
    post '/follow/:uuid', to: 'profiles#follow', as: 'profile_follow'
    post '/unfollow/:uuid', to: 'profiles#unfollow', as: 'profile_unfollow'
  end

  get '/messages/:user_uuid', to: 'messages#index', as: :users_conversations
  get '/messages/:sender_uuid/:adressee_id', to: 'messages#new', as: :messages_new
  get '/conversation/:thread_uuid', to: 'messages#show', as: :conversation_show
  post '/conversation/:thread_uuid', to: 'messages#create', as: :messages_create
  delete '/messages/:message_id', to: 'messages#destroy', as: :destroy_message

  post 'like/:kind/:id', to: 'reactions#like', as: 'like_activity'
  delete 'dislike/:kind/:id', to: 'reactions#dislike', as: 'dislike_activity'

  get 'comment/:kind/:id', to: 'comments#new', as: 'new_comment'
  post 'comment/:kind/:id', to: 'comments#create', as: 'create_comment'
  delete 'comment/:id', to: 'comments#destroy', as: 'destroy_comment'

  get '/posts/user/:uuid', to: 'posts#users_posts', as: :users_posts
  get '/posts/for_you/:uuid', to: 'posts#for_you', as: :posts_for_you
  get '/posts/popular/top', to: 'posts#popular', as: :posts_popular

  get '/events/user/:uuid', to: 'events#users_events', as: :users_events
  post 'events/:id/buy_ticket', to: 'events#buy_ticket', as: :buy_ticket_to_event
  get '/user/:uuid/tickets', to: 'events#show_tickets', as: :show_tickets


  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_comments.html.erb
<div class="row rounded-3 blue-bg my-1 p-2">
  <div class='row'>
    <div class='col-2' style='min-width: 175px;'>
      <%= link_to comment.user.full_name, users_profile_path(comment.user.uuid), class: 'btn btn-outline-success btn-sm', data: { turbo: false } %>
    </div>
    
    <div class='col'>
      <%= comment.content %>
    </div>
  </div>

  <div class='row'>
      <div class='col-2' style='min-width: 175px;'>
        <%= button_to 'Usuń komentarz', 
                      destroy_comment_path(id: comment.id),
                      class: 'btn btn-outline-danger my-1 btn-sm', 
                      method: :delete, data: { turbo: false } if object_author?(comment) || object_author?(root_object) %>
      </div>
      <div class='col'>
        <%= turbo_frame_tag :"#{comment.class.to_s}_#{comment.id}" do %>
          <%= link_to 'Skomentuj', new_comment_path(kind: :comment, id: comment.id), class: 'btn btn-primary btn-sm my-1' %>
        <% end unless comment.user.blocked?(current_user) %>
      </div>
  </div>
</div>

<% if comment.comments.present? %>
  <div class='w-75 float-end'>
    <%= render partial: 'shared/comments', 
               collection: comment.comments.includes(comments: { user: [:blocked_users] }, user: [:blocked_users]),
               as: :comment, 
               locals: { root_object: root_object } %>
  </div>
<% end %>

<div style="clear:both;"></div>

app/views/shared/_image_preview.html.erb
<%= content_tag :main, class: "container mx-auto pt-6 h-screen", data: { controller: 'image-upload-preview' } do %>
  <div class="flex flex-col">
    <label class="mb-4">Załącz obrazek</label>
    <%= file_field_tag :image, data: { target: 'image-upload-preview.input', action: 'image-upload-preview#setImagePreview' }%>
  </div>
  <div class="flex flex-col items-center justify-center border mt-12 h-4/5">
    <%= image_tag '', class: 'h-5/6 w-5/6 object-contain object-center', 
          data: { target: 'image-upload-preview.preview' }  %>
  </div>
<% end %>